
* Amazon Insiders
** Optimistic transaction approach for the DynamoDB
    It has only one version for a key-value pair. It obeys LWW (Last Writer Win) policy.
    Relies on time synchronization algorithms. 
**** Why not to use vector clocks?
** Number of machines per zone
** juju
** Amazon WebServices uses REST Architecture

** Amazon S3 BLOB. Eventual Consistency
   Files up to 5 terabytes.
   How it actually works? What replication algorithms?
   How many replicas. How is Load balancing performed?
** Amazon Route 53
   monitor the health and performance of your web applications,
   web servers, and other resources.
*** DNS failover
    you can configure DNS failover by associating health checks
    with your resource record sets. 
** Amazone ElasticCache
   web service that makes it easy to deploy,
   operate, and scale an in-memory data store or cache in the cloud.
** Does Amazon plan to create it's own app (web service) for deployment?
   Like Docker, SaltStack, Puppet, etc.
** AWS Database Migration Service
   Do you currently store relational data in an on-premises Oracle, SQL Server,
   MySQL, MariaDB, or PostgreSQL database? Would you like to move it to the AWS cloud
   with virtually no downtime so that you can take advantage of the scale,
   operational efficiency, and the multitude of data storage options that
   are available to you?

** Deployment Procedures Route 53
   Don't have rigid release or deployment schedules.  Individual developers
   are responsible for verifying their changes in the staging environment and
   pushing their changes into production. Each step of the pipeline is referred to
   as a "wave" and consists of some portion of our fleet. After each wave of the pipeline,
   the change can be verified -- this can include automatic, scheduled and
   manual testing as well as the verification of service metrics.
*** Stages:
    + Dev
    + Staging
    + Production

** On 20 AUG 2015 AWS announced a plug-in for Titan that allows it to use DynamoDB as a storage backend.
** Rumored to use Gossip Failure Detector in AWS EC2 and S3 (Rumored).
   Is it True?

* Practice
** Algorithms and Data Structures
*** Graph Theory
    - [X] https://www.hackerrank.com/challenges/floyd-city-of-blinding-lights
*** Dynamic Programming
    - [ ] https://www.hackerrank.com/challenges/stockmax
    - [ ] https://www.hackerrank.com/challenges/string-reduction
    - [ ] https://www.hackerrank.com/challenges/common-child
      
