
* Test of interaction with OS
  The essential part of non-functional testing is to verify the interaction with OS.
  cases: Memory leak, too many opened files left, etc.
* SQL queries is essentially the program written fully in Functional Language
  In fact, when you compose SQL queries you, essentially use higher order
  function like `map`, `filter`, `mapReduce` to retrieve and edit data. It implies
  that you can use your skills in Functional Programming to compose complex SQL queries
  rather than train them from the scratch
* What the Software Architecture is about
  The SA typically features those aspects of a system which are the hardes to be edited 
  or substituted. One of the purposes of SA is to represent (or catch the essense) of the system
  as early as possible. The retionale is that we can analyse and evaluate this representation 
  and reveal pluses and minuses
* Possible Answers (Non-Functional Requirements)
  1. [ ] Accessibility
  2. [ ] Availability
  3. [ ] Exploitability
  4. [ ] Extensibility
  5. [ ] Interoperability
  6. [ ] Maintainability
  7. [ ] Modifiability
  8. [ ] Performance
  9. [ ] Portability
  10. [ ] Reliability
  11. [ ] Scalability
  12. [ ] Security
  13. [ ] Supportability
  14. [ ] Testability
  15. [ ] Usability
* Architectual Style deals with non-functional requirements
