
* TODO Pass assessment for D3
** TODO Prepare for questions
*** What is D3? What are requirements for D3? What are destinctions from D4 and D2?
*** Consider the project and describe the timeline
*** How do you estimate time for tasks?
*** Describe your biggest achevement
*** Conflicts? Have you been inveolved in conflicts? Describe this experience
*** Continious integration process
*** How do you do the extimation
**** Make task decomposition
**** Can some parts be done concurrently? How do you collect risks -- how does it influence the schedule?
**** Do you review your estimates? Can you provide numbers for evaluation the accuracy of estimation
*** Describe lifecicle of sprints.
**** Events: grooming, duration, retrospective, the result, hand off to QA. Scrum Master. User stories => tasks
*** Trouble shooting technics
**** Debug (dbg), Reproduction, logging, destributed over severity, Code Reviewing
*** Why is code review is important?
**** Follow the codestyle, look from another perspective, verify compatability
*** What techinques do you use to garante reutines respons in time? Will react in time?
**** Destributing priorities of tasks. Implementing fear shearing. Hard testing.
