
* Слом мафией
  Мафии есть смысл ломать только в том случае,
  если это дает им мгновенную победу
* Голосование на попиле с тобой в условиях критики когда ты красный
  Если второй игрок готов кинуть руку в себя или активно агитирует на голосование в другого,
  то он КРАСНЫЙ. Иначе он просто заголосовывает тебя и все.
* Определение лжешерифа по его намерению голосовать
  Если кондидат на шерифство при найденном черном говорит что будет голосовать в другого
  и "дает тому возможность быть черным" скорее всего он ЛЖЕШЕРИФ
* Есть смысл прислушиваться и играть в команде с играком, которого считаешь точно красным
* Игра красным при трех шерифах.
  С большой долей вероятности 2 из 3 шерифов черные. Вероятность того что шериф уходит
  самострелом в такой ситуации очень мала
* Выявление истинного шерифа за красных
  Метод заключается в том что бы поставить себя на место шерифа и постараться понять 
  логику и вероятность его действий. Если она абсурдна или маловероятна, то делать 
  вывод о том что он лжешериф
* Перевод подозрения
  Если для стола с большой вероятностью игрок черный, а другой говорит что тот красный 
  и "втапливает красному", то уходит переворачивающий игрок
* Игра в уадайке с тремя игроками
  Как правило, если все три игрока под подозрением, тактика черных ловить руку красных,
  что бы сломать. Если игрок явно первый выбрасывает руку -- маловероятно, что он черный
* Признание черного в черноте
  Иногда можно вскрываться черным если тебя заголосовывают оба своих черных.
  Не забывать дать отстрел
* Игра при одном шерифе
  Вскрываешься красной проверке и просишь прикрыть
